//! Generation of the documentation the model owns (R1, `CM-01`).
//!
//! The generated file is committed, so a reviewer sees the diff. `xtask
//! check-model` regenerates it in memory and fails if the committed bytes
//! differ, which is what makes the model the single source rather than merely
//! the first source.

use core::fmt::Write as _;

use crate::Model;

/// Where the generated conformance table is committed.
pub const CONFORMANCE_PATH: &str = "CONFORMANCE.md";

/// Render `CONFORMANCE.md` from the ID register.
///
/// The index is generated rather than written, so that an ID cannot exist in
/// the documentation without a register row, or in the register without
/// appearing in the documentation (R2, R1, `CM-02`).
pub fn render_conformance(model: &Model) -> String {
    let mut out = String::new();
    let w = &mut out;
    let _ = writeln!(
        w,
        "<!-- @generated by `cargo xtask check-model --write` from model/ids.toml. -->"
    );
    let _ = writeln!(
        w,
        "<!-- Do not edit. R1: the model is the single source. -->"
    );
    let _ = writeln!(w);
    let _ = writeln!(w, "# CONFORMANCE");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "The conformance ID register. Every test name ends in its ID; a test whose"
    );
    let _ = writeln!(
        w,
        "ID is not listed here fails `cargo xtask check-model`, and so does an ID"
    );
    let _ = writeln!(w, "listed here with no scenario and no test (`CM-02`).");
    let _ = writeln!(w);
    let _ = writeln!(w, "The three honesty levels (R2):");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Level | Meaning |");
    let _ = writeln!(w, "| --- | --- |");
    let _ = writeln!(
        w,
        "| `some-true` | A fact reproduced from an authority. **Not established here.** |"
    );
    let _ = writeln!(
        w,
        "| `build` | Constructed here and validated against its oracle. Evidence, not a proof. |"
    );
    let _ = writeln!(w, "| `open` | Measured and reported. **Never asserted.** |");
    let _ = writeln!(w);
    let _ = writeln!(
        w,
        "`cargo xtask audit-limits` fails if any code path returns an error the"
    );
    let _ = writeln!(w, "model does not sanction.");

    // The classes are read off the register, not listed here. A list would be a
    // taxonomy this file asserts and the register does not have, and the first
    // symptom would be a heading with nothing under it --- a document claiming
    // coverage of a class that has no IDs. `suite` is the grouping the register
    // already carries, so it is the one used.
    let mut suites: Vec<&str> = model.ids.id.iter().map(|r| r.suite.as_str()).collect();
    suites.sort_unstable();
    suites.dedup();

    for suite in suites {
        let rows: Vec<_> = model.ids.id.iter().filter(|r| r.suite == suite).collect();
        if rows.is_empty() {
            continue;
        }
        let _ = writeln!(w);
        let _ = writeln!(w, "## {suite}");
        let _ = writeln!(w);
        let _ = writeln!(w, "| ID | Level | Statement |");
        let _ = writeln!(w, "| --- | --- | --- |");
        for r in rows {
            let statement = r.statement.replace('\n', " ").replace('|', "\\|");
            let _ = writeln!(
                w,
                "| `{}` | `{}` | {} |",
                r.id,
                r.level.as_str(),
                statement.trim()
            );
        }
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Cited authorities");
    let _ = writeln!(w);
    let _ = writeln!(w, "Never re-derived, vendored, or gated on.");
    let _ = writeln!(w);
    let _ = writeln!(w, "| Authority | Citation | Evidence here |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for a in &model.authorities.authority {
        let citation = a.citation.replace('\n', " ").replace('|', "\\|");
        let realized = if a.realized_by.is_empty() {
            "--".to_string()
        } else {
            a.realized_by
                .iter()
                .map(|i| format!("`{i}`"))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let _ = writeln!(w, "| `{}` | {} | {realized} |", a.id, citation.trim());
    }

    let _ = writeln!(w);
    let _ = writeln!(w, "## Claims that are not conformance IDs");
    let _ = writeln!(w);
    let _ = writeln!(w, "| ID | Level | Claim |");
    let _ = writeln!(w, "| --- | --- | --- |");
    for c in &model.ledger.claim {
        let statement = c.statement.replace('\n', " ").replace('|', "\\|");
        let _ = writeln!(
            w,
            "| `{}` | `{}` | {} |",
            c.id,
            c.level.as_str(),
            statement.trim()
        );
    }

    out
}
